import Head from "next/head";
import { signOut } from "next-auth/client";

const Home = () => {
    return (
        <div>
            <Head>
                <title>Fancy Todo App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <button onClick={() => signOut()}>signOut</button>
        </div>
    );
};

export default Home;
